language: cpp
os: linux
compiler:
  - gcc
  - clang
env:
  - CXX_VER=3.4
  - CXX_VER=4.6
  - CXX_VER=4.7
  - CXX_VER=4.8
matrix:
  exclude:
    - compiler: gcc
      env: CXX_VER=3.4
    - compiler: clang
      env: CXX_VER=4.6
    - compiler: clang
      env: CXX_VER=4.7
    - compiler: clang
      env: CXX_VER=4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.7
      - g++-4.8
install:
  - |
    if [ "$CXX_VER" == "4.7" -o "$CXX_VER" == "4.8" ] ; then
      echo "using gcc : $CXX_VER : g++-$CXX_VER ;" > ~/user-config.jam;
    fi
  - |
    if [ "$CXX" == "clang++" ] ; then
      echo "using clang ;" > ~/user-config.jam;
    fi
script:
  - git clone "https://github.com/boostorg/boost.git"
  - cd boost
  -   git submodule init --
        libs/test
        libs/config
        libs/wave
        libs/timer
        libs/chrono
        libs/system
        libs/core
        libs/predef
        libs/type_traits
        libs/assert
        libs/mpl
        libs/preprocessor
        libs/utility
        libs/smart_ptr
        libs/ratio
        libs/function
        libs/static_assert
        libs/throw_exception
        libs/exception
        libs/detail
        libs/integer
        libs/typeof
        libs/bind
        libs/io
        libs/numeric/conversion
        libs/iterator
        libs/optional
        libs/move
        libs/lexical_cast
        libs/range
        libs/concept_check
        libs/array
        libs/functional
        libs/container
        libs/math
        libs/xpressive
        libs/proto
        libs/fusion
        libs/conversion
        tools/build
        tools/inspect
  -   git submodule update
  -   git submodule foreach git checkout master
  -   cd libs
  -     git clone "https://github.com/sabel83/metaparse.git"
  -   cd ..
  -   cat ~/user-config.jam || true
  -   if [ "$CXX" == "g++"     ] ; then export TOOLSET=gcc;   fi
  -   if [ "$CXX" == "clang++" ] ; then export TOOLSET=clang; fi
  -   ./bootstrap.sh --with-toolset=$TOOLSET
  -   ./b2 headers
  -   cd libs
  -     cd test/build
  -       ../../../b2 -d+2
  -     cd ../..
  -     cd metaparse/build
  -       ../../../b2 -d+2

