language: cpp
os: linux
compiler:
  - gcc
  - clang
script:
  - git clone "https://github.com/boostorg/boost.git"
  - cd boost
  -   git submodule init -- libs/test
  -   git submodule init -- libs/config
  -   git submodule init -- libs/wave
  -   git submodule init -- libs/timer
  -   git submodule init -- libs/chrono
  -   git submodule init -- libs/system
  -   git submodule init -- libs/core
  -   git submodule init -- libs/predef
  -   git submodule init -- libs/type_traits
  -   git submodule init -- libs/assert
  -   git submodule init -- libs/mpl
  -   git submodule init -- libs/preprocessor
  -   git submodule init -- tools/build
  -   git submodule init -- tools/inspect
  -   git submodule update
  -   cd libs
  -     git clone "https://github.com/sabel83/metaparse.git"
  -   cd ..
  -   ./bootstrap.sh
  -   cd libs
  -     cd test/build
  -       ../../../b2
  -     cd ../..
  -     cd metaparse/test
  -       ../../../b2
