language: cpp
os: linux
matrix:
  include:
    - compiler: clang
      env: CXX_VER=3.4 TOOLSET=clang STD=c++98
    - compiler: clang
      env: CXX_VER=3.5 TOOLSET=clang STD=c++98
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.5
          packages:
            - clang-3.5
      install:
        - "echo \"using clang : 3.5 : clang++-3.5 ;\" > ~/user-config.jam"
    - compiler: clang
      env: CXX_VER=3.6 TOOLSET=clang STD=c++98
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      install:
        - "echo \"using clang : 3.6 : clang++-3.6 ;\" > ~/user-config.jam"
    - compiler: gcc
      env: CXX_VER=4.6 TOOLSET=gcc STD=c++98
    - compiler: gcc
      env: CXX_VER=4.7 TOOLSET=gcc STD=c++98
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.7
      install:
        - "echo \"using gcc : 4.7 : g++-4.7 ;\" > ~/user-config.jam"
    - compiler: gcc
      env: CXX_VER=4.8 TOOLSET=gcc STD=c++98
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
      install:
        - "echo \"using gcc : 4.8 : g++-4.8 ;\" > ~/user-config.jam"
    - compiler: gcc
      env: CXX_VER=4.8 TOOLSET=gcc STD=c++11
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
      install:
        - "echo \"using gcc : 4.8 : g++-4.8 ;\" > ~/user-config.jam"
    - compiler: gcc
      env: CXX_VER=4.9 TOOLSET=gcc STD=c++98
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      install:
        - "echo \"using gcc : 4.9 : g++-4.9 ;\" > ~/user-config.jam"
script:
  - git clone "https://github.com/boostorg/boost.git"
  - cd boost
  -   git submodule init --
        libs/test
        libs/config
        libs/wave
        libs/timer
        libs/chrono
        libs/system
        libs/core
        libs/predef
        libs/type_traits
        libs/assert
        libs/mpl
        libs/preprocessor
        libs/utility
        libs/smart_ptr
        libs/ratio
        libs/function
        libs/static_assert
        libs/throw_exception
        libs/exception
        libs/detail
        libs/integer
        libs/typeof
        libs/bind
        libs/io
        libs/numeric/conversion
        libs/iterator
        libs/optional
        libs/move
        libs/lexical_cast
        libs/range
        libs/concept_check
        libs/array
        libs/functional
        libs/container
        libs/math
        libs/xpressive
        libs/proto
        libs/fusion
        libs/conversion
        tools/build
        tools/inspect
  -   git submodule update
  -   git submodule foreach git checkout master
  -   cd libs
  -     git clone "https://github.com/sabel83/metaparse.git"
  -   cd ..
  -   cat ~/user-config.jam || true
  -   ./bootstrap.sh --with-toolset=$TOOLSET
  -   ./b2 headers
  -   cd libs
  -     cd test/build
  -       ../../../b2 -d+2
  -     cd ../..
  -     cd metaparse/build
  -       ../../../b2 -d+2 cxxflags="-std=$STD -ftemplate-depth=512"

