language: cpp
os: linux
matrix:
  include:
    - compiler: clang
      env: CXX_VER=3.4 TOOLSET=clang STD=c++98
      addons: &doc
        apt:
          packages:
            - doxygen
            - xsltproc
    - compiler: clang
      env: CXX_VER=3.5 TOOLSET=clang STD=c++98
      addons: &clang35
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.5
          packages:
            - clang-3.5
            - doxygen
            - xsltproc
      install:
        - "echo \"using clang : 3.5 : clang++-3.5 ;\" > ~/user-config.jam"
    - compiler: clang
      env: CXX_VER=3.5 TOOLSET=clang STD=c++11
      addons: *clang35
      install:
        - "echo \"using clang : 3.5 : clang++-3.5 ;\" > ~/user-config.jam"
    - compiler: clang
      env: CXX_VER=3.6 TOOLSET=clang STD=c++98
      addons: &clang36
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - doxygen
            - xsltproc
      install:
        - "echo \"using clang : 3.6 : clang++-3.6 ;\" > ~/user-config.jam"
    - compiler: clang
      env: CXX_VER=3.6 TOOLSET=clang STD=c++11
      addons: *clang36
      install:
        - "echo \"using clang : 3.6 : clang++-3.6 ;\" > ~/user-config.jam"
    - compiler: gcc
      env: CXX_VER=4.6 TOOLSET=gcc STD=c++98
      addons: *doc
    - compiler: gcc
      env: CXX_VER=4.7 TOOLSET=gcc STD=c++98
      addons: &gcc47
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.7
            - doxygen
            - xsltproc
      install:
        - "echo \"using gcc : 4.7 : g++-4.7 ;\" > ~/user-config.jam"
    - compiler: gcc
      env: CXX_VER=4.7 TOOLSET=gcc STD=c++11
      addons: *gcc47
      install:
        - "echo \"using gcc : 4.7 : g++-4.7 ;\" > ~/user-config.jam"
    - compiler: gcc
      env: CXX_VER=4.8 TOOLSET=gcc STD=c++98
      addons: &gcc48
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
            - doxygen
            - xsltproc
      install:
        - "echo \"using gcc : 4.8 : g++-4.8 ;\" > ~/user-config.jam"
    - compiler: gcc
      env: CXX_VER=4.8 TOOLSET=gcc STD=c++11
      addons: *gcc48
      install:
        - "echo \"using gcc : 4.8 : g++-4.8 ;\" > ~/user-config.jam"
    - compiler: gcc
      env: CXX_VER=4.9 TOOLSET=gcc STD=c++98
      addons: &gcc49
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - doxygen
            - xsltproc
      install:
        - "echo \"using gcc : 4.9 : g++-4.9 ;\" > ~/user-config.jam"
    - compiler: gcc
      env: CXX_VER=4.9 TOOLSET=gcc STD=c++11
      addons: *gcc49
      install:
        - "echo \"using gcc : 4.9 : g++-4.9 ;\" > ~/user-config.jam"
script:
  - echo "using doxygen ;" >> ~/user-config.jam
  - echo "using xsltproc ;" >> ~/user-config.jam
  - echo "using quickbook ;" >> ~/user-config.jam
  - git clone "https://github.com/boostorg/boost.git .boost"
  - cd .boost
  -   git submodule init --
        libs/test
        libs/config
        libs/wave
        libs/timer
        libs/chrono
        libs/system
        libs/core
        libs/predef
        libs/type_traits
        libs/assert
        libs/mpl
        libs/preprocessor
        libs/utility
        libs/smart_ptr
        libs/ratio
        libs/function
        libs/static_assert
        libs/throw_exception
        libs/exception
        libs/detail
        libs/integer
        libs/typeof
        libs/bind
        libs/io
        libs/numeric/conversion
        libs/iterator
        libs/optional
        libs/move
        libs/lexical_cast
        libs/range
        libs/concept_check
        libs/array
        libs/functional
        libs/container
        libs/math
        libs/xpressive
        libs/proto
        libs/fusion
        libs/conversion
        tools/build
        tools/inspect
  -   git submodule init --
        libs/program_options
        libs/filesystem
        libs/spirit
        libs/foreach
        libs/iostreams
        libs/algorithm
        libs/tuple
        libs/any
        libs/type_index
        libs/unordered
        libs/align
        libs/tokenizer
        tools/boostbook
        tools/quickbook
  -   git submodule update
  -   git submodule foreach git checkout master
  -   cd libs
  -     mkdir metaparse
  -     mv ../../* metaparse
  -   cd ..
  -   cd tools/boostbook
  -      wget http://abel.web.elte.hu/boost_book_dependencies/docbook-xml-4.2.zip
  -      wget http://abel.web.elte.hu/boost_book_dependencies/docbook-xsl-1.75.2.tar.gz
  -      wget http://abel.web.elte.hu/boost_book_dependencies/fop-0.94-bin-jdk1.4.tar.gz
  -     ./setup_boostbook.sh
  -   cd ../..
  -   cat ~/user-config.jam
  -   ./bootstrap.sh --with-toolset=$TOOLSET
  -   ./b2 headers
  -   cd libs
  -     cd test/build
  -       ../../../b2 -d+2
  -     cd ../..
  -     cd metaparse
  -       cd build
  -         ../../../b2 -d+2 cxxflags="-std=$STD -ftemplate-depth=512"
  -       cd ..
  -       cd doc
  -         ../../../b2 -d+2 cxxflags="-Wno-unused-local-typedefs"

