os: Visual Studio 2015
platform: x64
configuration: Debug

clone_folder: c:\build\boost_\libs\metaparse

init:
  - cd c:\build
  - git clone https://github.com/boostorg/boost.git
  - move boost_\libs\metaparse boost\libs
  - cd boost
  -   git submodule init --
        libs/test
        libs/config
        libs/wave
        libs/timer
        libs/chrono
        libs/system
        libs/core
        libs/predef
        libs/type_traits
        libs/assert
        libs/mpl
        libs/preprocessor
        libs/utility
        libs/smart_ptr
        libs/ratio
        libs/function
        libs/static_assert
        libs/throw_exception
        libs/exception
        libs/detail
        libs/integer
        libs/typeof
        libs/bind
        libs/io
        libs/numeric/conversion
        libs/iterator
        libs/optional
        libs/move
        libs/lexical_cast
        libs/range
        libs/concept_check
        libs/array
        libs/functional
        libs/container
        libs/math
        libs/xpressive
        libs/proto
        libs/fusion
        libs/conversion
        libs/rational
        libs/winapi
        tools/build
        tools/inspect
  -   git submodule update
  -   git submodule foreach git checkout master

build_script:
  - cd ..\..
  - bootstrap.bat
  - b2 headers
  - cd libs
  -   cd test\build
  -     ..\..\..\b2 -d+2
  -   cd ..\..
  -   cd metaparse
  -     cd build
  -       ..\..\..\b2 -d+2
