os: Visual Studio 2015
platform: x64
configuration: Debug

clone_folder: c:\build\boost\libs\metaparse

init:
  - cd c:\build
  - move boost boost_
  - c:\python27\python.exe c:\build\boost_\libs\metaparse\tools\build_environment.py --dep_json boost_\libs\metaparse\tools\deps.json --action checkout
  - move boost_\libs\metaparse boost\libs
  - cd boost\libs\metaparse

build_script:
  - cd ..\..
  - bootstrap.bat
  - b2 headers
  - cd libs
  -   cd test\build
  -     ..\..\..\b2 -d+2
  -   cd ..\..
  -   cd metaparse
  -     cd build
  -       ..\..\..\b2 -d+2
